name: 4. Build Loop 
run-name: Trigger Build Loop (${{ github.ref_name }})
on:
  workflow_dispatch:
  schedule:
    - cron: "33 7 * * 0" # Sunday at UTC 7:33

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger target workflow
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          curl --fail -X PUT \
            -H "Authorization: Bearer ${GH_PAT}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/build_loop.yml/enable

          curl --fail -X POST \
            -H "Authorization: Bearer ${GH_PAT}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/build_loop.yml/dispatches \
            -d '{"ref":"${{ github.ref_name }}", "inputs": {"is_scheduled": "true"}}'
